POST http://localhost:3001/api/order HTTP/1.1
content-type: application/json

{
    "productId": -1,
    "quantity": 100
}
###
POST http://localhost:3001/api/order HTTP/1.1
content-type: application/json

{
    "productId": "asd",
    "quantity": 100
}
###
POST http://localhost:3001/api/order HTTP/1.1
content-type: application/json

{
    "productId": 1064,
    "quantity": 10000000
}